### ISSUE TITLE
nvrtc error

### ISSUE THREAD

**Issue by kassasin** [hojae-io/ModelBasedFootstepPlanning-IROS2024#2]
When I run train scrip which using GPU,an error occured."nvrtc: error: invalid value for --gpu-architecture (-arch)"

**Comment by kassasin** [comment]
My GPU is 4090,nvidia driver is 525.60.11,cuda is 12.4 .

**Comment by kassasin** [comment]
I have fixed this problem by reinstall torch torchvision torchaudio to match my cuda version .
"pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124"

**Comment by ZimengYuan** [comment]
have you ever uninstall torch including the related toolkits?  if I run the command, the system thinks I meet the version.

**Comment by kassasin** [comment]
Yes, I had uninstall torch .
